package FML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Type extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Type() {
    super(0xa92a6e05bbaf47feL, 0x8d9a530de3a9cd83L, 0x7e31924bbfe03c00L, "Type", "r:60a88e45-9990-404e-9ae9-38b67012c5e4(FML.structure)/9093209976677088256");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_String_0 = new EnumerationDescriptor.MemberDescriptor("String", "String", 0x7e31924bbfe03c01L, "r:60a88e45-9990-404e-9ae9-38b67012c5e4(FML.structure)/9093209976677088257");
  private final EnumerationDescriptor.MemberDescriptor myMember_Integer_0 = new EnumerationDescriptor.MemberDescriptor("Integer", "Integer", 0x7e31924bbfe03c02L, "r:60a88e45-9990-404e-9ae9-38b67012c5e4(FML.structure)/9093209976677088258");
  private final EnumerationDescriptor.MemberDescriptor myMember_Boolean_0 = new EnumerationDescriptor.MemberDescriptor("Boolean", "Boolean", 0x7e31924bbfe03c05L, "r:60a88e45-9990-404e-9ae9-38b67012c5e4(FML.structure)/9093209976677088261");
  private final EnumerationDescriptor.MemberDescriptor myMember_Float_0 = new EnumerationDescriptor.MemberDescriptor("Float", "Float", 0x7e31924bbfe03c09L, "r:60a88e45-9990-404e-9ae9-38b67012c5e4(FML.structure)/9093209976677088265");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xa92a6e05bbaf47feL, 0x8d9a530de3a9cd83L, 0x7e31924bbfe03c00L, 0x7e31924bbfe03c01L, 0x7e31924bbfe03c02L, 0x7e31924bbfe03c05L, 0x7e31924bbfe03c09L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_String_0, myMember_Integer_0, myMember_Boolean_0, myMember_Float_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_String_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "String":
        return myMember_String_0;
      case "Integer":
        return myMember_Integer_0;
      case "Boolean":
        return myMember_Boolean_0;
      case "Float":
        return myMember_Float_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
